### ISSUE TITLE
style: `NeuSearchBar` Initial UI Looks changes

### ISSUE THREAD

**Issue by deepraj02** [deepraj02/neubrutalism_ui#28]
Changing the initial look for `NeuSearchBar` widget when Called.

part of #24

**Comment by bahadirtrkalioglu** [comment]
Hello, could you give some details about this issue; I liked that project.

**Comment by deepraj02** [comment]
Hey dude @bahadirtrkalioglu , thanks for the Interest, it's basically a flutter Package which is packed with NeuBrutalist styled Widgets.
Read the README for more, and in case you still have any doubt just ping me✌️

**Comment by bahadirtrkalioglu** [comment]
Thanks, let's see what I can do for this project. I like this design style.

**Comment by deepraj02** [comment]
Suree @bahadirtrkalioglu 🔥
